auth:
  registry.cn-beijing.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/ingress-nginx/controller: registry.cn-beijing.aliyuncs.com/rizhiyi/ingress-nginx-controller

