auth:
  registry.cn-beijing.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/v2/ingress-nginx/controller/manifests/v1.2.1: registry.cn-beijing.aliyuncs.com/rizhiyi/ingress-nginx-controller
