name: image-sync
on:
  workflow_dispatch:

env:
  IMAGE_SYNCER_VERSION: v1.3.0
  DOCKERHUB_USERNAME: ${{ secrets.USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        
    - name: init config.yaml with env
      run: |
        sed -i "s#USERNAME#${DOCKERHUB_USERNAME}#g" config.yaml
        sed -i "s#PASSWORD#${DOCKERHUB_PASSWORD}#g" config.yaml
        
    - name: sync images
      run: |
        ./image-syncer --proc=20 --config=config.yaml --namespace=rizhiyi --registry=registry.cn-beijing.aliyuncs.com --retries=1
